name: basic3

on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    if: github.repository == 'kryz81/learn_github_actions'
    steps:
      - run: echo "hello"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    if: ${{ !cancelled() }}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 22
      - run: node -v
      - uses: actions/checkout@v3
      - run: npm i
      - run: npm i -g jest
      - run: node test
