name: basic9

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      cache_key: ${{ steps.cache_key.outputs.CACHE_KEY }}
    steps:
      - uses: actions/checkout@v4
      - run: echo "CACHE_KEY=${{ hashFiles('package-lock.json') }}" >> $GITHUB_OUTPUT
        id: cache_key
      - uses: actions/cache@v4
        with:
          key: npm_cache_${{ hashFiles('package-lock.json') }}
          path: node_modules
        id: cache
      - run: npm ci
        if: steps.cache.outputs.cache-hit != 'true'

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
        if: needs.build.outputs.cache_key != 'true'
      - run: npm test
