name: basic2

on:
  label:
    types:
      - created
  issue_comment:
    types:
      - created
    labels:
      - bug
  push:
    branches:
      - feature/*
    paths:
      - 'show_secret.js'
  workflow_dispatch:
    inputs:
      title:
        description: 'title'
        required: true
        type: string
  repository_dispatch:
    types: [build]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: ls
    - run: echo 'Hello ${{ inputs.title }}'
