name: basic15

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  job1:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - run: echo "${{ github.workflow }}-${{ github.ref }}"
