name: basic6

on: workflow_dispatch

jobs:
  build:
    name: custom job namesssssssssss
    strategy:
      matrix:
        node_version: [20, 22]
        include:
          - node_version: 18
      fail-fast: false
    runs-on: ubuntu-latest
    container:
      image: node:20
      env:
        NODE_ENV: development
      ports:
        - 5000:5000
    steps:
      - run: node -v

  report:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ always() }}
    steps:
      - run: echo "1"
