name: basic4

on:
  workflow_dispatch:
  create:
  schedule:
    - cron: '*/5 0 * * *'

jobs:
    what:
      runs-on: ubuntu-latest
      steps:
        - run: echo "${{ github.ref }}"

    build:
      runs-on: ubuntu-latest
      outputs:
        hash: ${{ steps.hash1.outputs.HASH }}
      steps:
        - uses: actions/checkout@v4
        - run: echo "HASH=${{ hashFiles('test.txt') }}" >> $GITHUB_OUTPUT
          id: hash1

    test:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - run: echo "The hash is ${{ needs.build.outputs.hash }}"
