name: basic1

on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      APP: v1
    steps:
      - run: echo "${{ github.action }}, ${{ github.actor }}"
        id: first_step
      - run: echo "${{ github.repository }}, ${{ github.ref }}"
      - run: echo "${{ github.workspace }}"
      - run: echo "${{ runner.os }}"
      - run: echo "${{ job.status }}"
      - run: echo "${{ env.APP }}"

  job2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ vars.TITLE }}"

  job3:
    runs-on: ubuntu-latest
    container: node:20
    env:
      PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - run: node show_secret.js
