name: basic10

on: workflow_dispatch

permissions:
  actions: write

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: gh repo list
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
