name: basic12

on: workflow_dispatch

env:
  VERSION: '1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$VERSION"
      - run: echo "VERSION=2" >> $GITHUB_ENV
      - run: echo "$VERSION"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$VERSION"
