name: basic14

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        id: cache
        with:
          path: ~/.npm
          key: npm_cache
      - run: echo "${{ steps.cache.outputs.cache-hit == 'true' }}"
      - run: npm ci
